### ISSUE TITLE
https://igpi.ga/whizzzkid/media?count=3

### ISSUE THREAD

**Issue by croofec** [whizzzkid/instagram-reverse-proxy#26] opened 2018-03-15 22:58 UTC
"code": 2,
"desc": "Failed to fetch from Instagram.",
"info": "encountered: TypeError: Cannot read property 'id' of undefinedfetched:

on https://igpi.ga/whizzzkid/media?count=3 and on my feed.

it looks like something has changed on instagram

**Comment by whizzzkid** [comment] 2018-03-16 02:49
this is a duplicate of #25

**Closed as completed by whizzzkid** 2018-03-16 02:49 UTC
Labels: duplicate
